### ISSUE TITLE
Use Delauney Triangulation

### ISSUE THREAD

**Issue by Shitiz1708** [utkarshnath/Facial-Expression-Detection#1]
Instead of taking mean distance from a point , use delauney trianguation method then use covariance.
It increases SVM accuracy to 87%.
Source:-
https://cs.aston.ac.uk/~fariad/publications/ID279.pdf
PS: I am working in the same field :)

**Comment by utkarshnath** [comment]
Nice Shitiz 👍 

but I am not working on it currently, I did this in my 3rd semester, have just uploaded it late
